pipeline {  
    agent any // 或者指定一个具体的agent标签，如果Jenkins环境中有多个agent  
    triggers {  
        githubPush() // 监听GitHub push事件  
    }  
    stages {  
        stage('Build') {  
            steps {  
                script {  
                    // 切换到包含Dotnet项目的目录（如果Jenkinsfile不在项目根目录）  
                    // sh 'cd dotnet/project'  
                        
                    // 这里假设.NET SDK已安装在Jenkins Agent上  
                    sh 'dotnet restore'  
                    sh 'dotnet build -c Release'  
                }  
            }  
        }  
  
    }  
}
